languages: ruby
rvm:
  - 2.5.1
bundler_args: --without development production
cache: bundler
services:
  - postgresql
  - redis-server
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rails db:schema:load --trace
  - bundle exec rspec
