development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

production:
  adapter: mysql2
  encoding: utf8
  user: laxman
  password: chatouncem*
  pool: 5
  timeout: 5000
  host: localhost
  min_messages: WARNING
  database: chatounce_production