development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: chatounce_production
  pool: 5
  username: laxman
  password: chatouncem*
  socket: /tmp/mysql.sock